phraseapp:
  project_id: 8c510fd863c8e73c7801c1b84cf461df
  pull:
    targets:
      file: ./locales/<locale_name>.js
      params:
        update_translations: true
        file_format: node_json