phraseapp:
  project_id: 8c510fd863c8e73c7801c1b84cf461df
  file_format: node_json
  push:
    sources:
    - file: ./locales/<locale-name>.js
      params:
        update_translations: true
        file_format: node_json
  pull:
    targets:
    - file: ./locales/<locale-name>.js
      params:
        file_format: node_json